apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.thenickfish.github.com
spec:
  scope: Namespaced
  group: thenickfish.github.com
  names:
    kind: XBucket
    plural: xbuckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              bucket_name:
                  description: Name for the bucket
                  type: string
              region:
                  description: Region to deploy the bucket into
                  type: string
              
          status:
            type: object
            properties:
              bucket_name:
                  type: string
              